pipeline {
    agent any
    tools {
        nodejs "nodejs"
    }
    environment {
        HOST1 = "10.10.200.78"
        HOST2 = "10.10.100.135"
        BACKEND_URL = "10.10.1.21:3000"
        IMAGE_NAME = "kmilavaut/omnicloud-frontend"
        TAG = "latest"
    }

    stages {
        stage ("Clone Repository") { 
            steps {
                git branch: "master", url: "https://github.com/cmlavaut/omnicloud.git", credentialsId: "github"
            }
        }

        stage ("Install Dependencies") {
            steps {
                dir ("app-frontend") {
                    sh 'npm install'
                }
            }
        }

        stage ("Build Docker Image") {
            steps {
                dir ("app-frontend") {
                    sh "docker build -t ${IMAGE_NAME}:${TAG} ."
                }
            }
        }

        stage ("Push to Docker Hub") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push ${IMAGE_NAME}:${TAG}
                    """
                }
            }
        }

        stage ("Deploy to FRONTEND1-Docker") {
            steps {
                sshagent (["ec2-ssh-pem"]) {
                    withCredentials([usernamePassword(
                        credentialsId: 'rds-db-credentials',
                        usernameVariable: 'DB_USER',
                        passwordVariable: 'DB_PASS'
                    )]){
                        sh """
                        ssh ec2-user@${HOST1} "
                            docker pull ${IMAGE_NAME}:${TAG} &&
                            docker stop app || true &&
                            docker rm app || true &&
                            pkill node || true &&
                            pm2 delete all || true &&
                            docker run -d -p 3000:3000 --name app \
                              -e DB_HOST=${DB_HOST} \
                              -e DB_USER=${DB_USER} \
                              -e DB_PASS=${DB_PASS} \
                              -e DB_NAME=${DB_NAME} \
                              ${IMAGE_NAME}:${TAG}
                        "
                        """
                    }
                }
            }
        }

        stage ("Deploy to FRONTEND2-Docker") {
            steps {
                sshagent (["ec2-ssh-pem"]) {
                    withCredentials([usernamePassword(
                        credentialsId: 'rds-db-credentials',
                        usernameVariable: 'DB_USER',
                        passwordVariable: 'DB_PASS'
                    )]){
                        sh """
                        ssh ec2-user@${HOST2} "
                            docker pull ${IMAGE_NAME}:${TAG} &&
                            docker stop app || true &&
                            docker rm app || true &&
                            pkill node || true &&
                            pm2 delete all || true &&
                            docker run -d -p 3000:3000 --name app \
                              -e DB_HOST=${DB_HOST} \
                              -e DB_USER=${DB_USER} \
                              -e DB_PASS=${DB_PASS} \
                              -e DB_NAME=${DB_NAME} \
                              ${IMAGE_NAME}:${TAG}
                        "
                        """
                    }
                }
            }
        }
    }
}

/* 
        stage ("Deploy to FRONTEND1") {
            steps {
                sshagent (["ec2-ssh-pem"]) {
                    sh """
                    scp -o StrictHostKeyChecking=no -r app-frontend ec2-user@${HOST1}:/home/ec2-user/
                    ssh ec2-user@${HOST1} "
                        cd /home/ec2-user/app-frontend &&
                        export BACKEND_URL=${BACKEND_URL} &&
                        npm install --production &&
                        pm2 delete app-frontend || true &&
                        pm2 start server.js --name app-frontend &&
                        pm2 save
                    "                 
                    """
                }
            }
        }

        stage ("Deploy to FRONTEND2") {
            steps {
                sshagent (["ec2-ssh-pem"]) {
                    sh """
                    scp -o StrictHostKeyChecking=no -r app-frontend ec2-user@${HOST2}:/home/ec2-user/
                    ssh ec2-user@${HOST2} "
                        cd /home/ec2-user/app-frontend &&
                        export BACKEND_URL=${BACKEND_URL} &&
                        npm install --production &&
                        pm2 delete app-frontend || true &&
                        pm2 start server.js --name app-frontend &&
                        pm2 save
                    "                 
                    """
                }
            }
        }

    }
    
}

 */