pipeline {
    agent any
    tools {
        nodejs "nodejs"
    }
    environment {
        HOST1 = "10.10.200.78"
        HOST2 = "10.10.100.135"
        BACKEND_URL = "10.10.1.21:3000"
    }

    stages {
        stage ("Clone Repository") { 
            steps {
                git branch: "master", url: "https://github.com/cmlavaut/omnicloud.git", credentialsId: "github"
            }
        }

        stage ("Install Dependencies") {
            steps {
                dir ("app-frontend") {
                    sh 'npm install'
                }
            }
        }

        stage ("Deploy to FRONTEND1") {
            steps {
                sshagent (["ec2-ssh-pem"]) {
                    sh """
                    scp -o StrictHostKeyChecking=no -r app-frontend ec2-user@${HOST1}:/home/ec2-user/
                    ssh ec2-user@${HOST1} '
                        cd /home/ec2-user/app-frontend &&
                        export BACKEND_URL=${BACKEND_URL}
                        npm install --production &&
                        pm2 delete app-frontend || true &&
                        pm2 start server.js --name app-frontend &&
                        pm2 save
                    '                 
                    """
                }
            }
        }

        stage ("Deploy to FRONTEND2") {
            steps {
                sshagent (["ec2-ssh-pem"]) {
                    sh """
                    scp -o StrictHostKeyChecking=no -r omnicloud/app-frontend ec2-user@${HOST2}:/home/ec2-user/
                    ssh ec2-user@${HOST2} '
                        cd /home/ec2-user/app-frontend &&
                        export BACKEND_URL=${BACKEND_URL}
                        npm install --production &&
                        pm2 delete app-frontend || true &&
                        pm2 start server.js --name app-frontend &&
                        pm2 save
                    '                 
                    """
                }
            }
        }

    }
    
}

