- name: Install Docker (moby)
  dnf:
    name:
      - docker
    state: present
    update_cache: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes 
 
 

